### ISSUE TITLE
Component registration fails with script setup

### ISSUE THREAD

**Issue by jcfauchet** [Trinovantes/vue-ssr-assets-plugin#1]
Hi,

Thank you for this plugin, it's gonna be really helpful !
I just tested it and it with your example seems there is a problem on registration with script setup syntax

I add console.log in the entryServer to print the ssrContext after renderToString operation and as you can see on the screenshot, for the route `/b` only the `App.vue` is registred while each component are well registred on other routes.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/21689610/164323682-9a13e0a5-c1fe-442f-adc1-8a3c6320ab0e.png">

Thanks :)

**Comment by Trinovantes** [comment]
Seems to only happen in production because `vue-loader` optimization ignores webpack's intermediate files from loaders and compiles the original template from source

Simplest solution is to modify the original `<script setup>` source but this may break source maps
