### ISSUE TITLE
Missing manifest from memory

### ISSUE THREAD

**Issue by Roylz** [Trinovantes/vue-ssr-assets-plugin#9]
Hi,

Thank you for working on this plugin, it worked very well.
However, I noticed the manifest seems not to be generated in memory when I integrate with HMR by using webpack-hot-middleware.

Is it possible we can add to support , or we can do the smiliar as [webpack-manifest-plugin ](https://www.npmjs.com/package/webpack-manifest-plugin#writetofileemit)
to have an option to write to disk?

**Comment by Trinovantes** [comment]
Did you mean that it is currently generating to memory when you use webpack-hot-middleware and would like an option to write force write to disk?

Right now when I run the example (`yarn exDev` in this repo), it already writes to disk `./dist/example/ssr-manifest.json`

**Comment by Roylz** [comment]
Sorry for the confusion.

I'm using webpack-dev-middleware instead of `--watch` directly from webpack. So the fileSystem is `memfs` for dev environemnt, and then it will try to find the manifest file from memory

For webpack-manifest-plugin, I mean if we can't not generate the manifest for memory, we can have a similar option in this plugin, so the manifest can be saved to disk, then we can access it with node `fs` indestead of `memfs`.

Hope this makes sense. Thank you.

**Comment by Trinovantes** [comment]
Wouldn't webpack-dev-middleware's `writeToDisk` option work? https://github.com/webpack/webpack-dev-middleware?tab=readme-ov-file#writetodisk

If not, can you provide an example repo of what's currently happening and what you would like to see?

**Comment by Roylz** [comment]
Sure, let me test it out and work on a repo for you

**Comment by Trinovantes** [comment]
Doesn't `writeToDisk` allow a function to filter what gets written to disk?

```js
writeToDisk: (filePath) => /ssr-manifest\.json/.test(filePath)
```
